### ISSUE TITLE
birth minute

### ISSUE THREAD

**Issue by misbach** [jc4p/natal-charts#1]
I love your natal chart API. I noticed that you don't take into account the persons birth minute. From my understanding that makes the chart meta date less accurate. Could you take into account the birth minute?

**Comment by jc4p** [comment]
Hey, I'm super happy someone's using this!! 😄 

I actually added [birth minute support](https://github.com/jc4p/natal-charts/commit/3e930e3da299360f938f8036079410d3b7f00e99#diff-f9c3e806936f9adebcd8226b6ebb4abd) a while back.

The `/chart` endpoint takes `birth_hour` and `birth_min` in its POST parameters. If the value is passed in from the parameters it's used for the chart calculation, but I didn't consider it a required parameter.  

The `/geocode` endpoint doesn't take a birth minute, since in that endpoint time of day is just used for calculating historical daylight savings it doesn't have any downstream effects on the chart calculation.

Let me know if it works on your end, closing this as already-fixed for now :)

**Comment by misbach** [comment]
Nice, It works. Thank you!
Do you by chance know of a free service that can take the results and generate a cool natal chart?
